version: "3.3"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST: $DATABASE_HOST
      POSTGRES_PORT: $DATABASE_PORT
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_DEBUG: $DATABASE_DEBUG
    ports:
      - 5432:5432
